name: Build for Termux (ARM64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compilar Executável para Termux
        run: |
          # Busca especificamente pelo projeto CLI ou o principal
          PROJECT_FILE=$(find . -name "*Cli.csproj" -o -name "RPGMakerDecrypter.csproj" | head -n 1)
          echo "Compilando projeto: $PROJECT_FILE"
          
          dotnet publish $PROJECT_FILE \
          -c Release \
          -r linux-arm64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish

      - name: Upload do Binário
        uses: actions/upload-artifact@v4
        with:
          name: RPGMakerDecrypter-Termux
          path: ./publish/

      - name: Upload do Binário
        uses: actions/upload-artifact@v4
        with:
          name: RPGMakerDecrypter-Termux-ARM64
          path: ./publish/RPGMakerDecrypter-cli
          
