name: Build uuksu CLI for Termux
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish for Android/Termux
        run: |
          # Procura o arquivo .csproj automaticamente
          PROJECT_PATH=$(find . -name "RPGMakerDecrypter.CLI.csproj")
          dotnet publish "$PROJECT_PATH" -c Release -r linux-arm64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./output
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpg-decrypter-uuksu-arm64
          path: ./output/RPGMakerDecrypter.CLI
